name: Swaroop SM
port: 1619
basepath: /testing
assets: assets
destination: public
permalink:
  style: :name
  pretty: true
tagged: tagged
archive: archive
homepage: home
include_assets:
 - css
 - js
 - fonts
remote:
 host: swaroopsm.com
 username: swaroop
 path: sites/swaroopsm.com
